apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-service-app
  template:
    metadata:
      labels:
        app: configuration-service-app
    spec:
     volumes:
          - name: bcephal-configuration-repository
            hostPath:
              path: /opt/bcephal-configuration-repository
     containers:
      - name: configuration-service-app
        image: localhost:5000/becphal-configuration-service-docker-image
        volumeMounts:
            - name: bcephal-configuration-repository
              mountPath: /opt/bcephal-configuration-repository
       
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service-svc
spec:
  selector:
    app: configuration-service-app
  type: NodePort
  ports:
  - port: 80
    nodePort: 32645
    targetPort: 8000
