ALTER TABLE BCP_SEC_USER_SESSION_LOG ADD COLUMN IF NOT EXISTS functionality VARCHAR(255);
ALTER TABLE BCP_SEC_USER_SESSION_LOG ADD COLUMN IF NOT EXISTS objectId BIGINT;
ALTER TABLE BCP_SEC_USER_SESSION_LOG ADD COLUMN IF NOT EXISTS rightLevel VARCHAR(50);