apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcephal-messenger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcephal-messenger-service
    
  template:
    metadata:
      labels:
        app: bcephal-messenger-service
    spec:
      volumes:
      - name: bcephal-messenger-repository
        hostPath:
          path: /opt/bcephal-messenger-repository
      containers:
      - name: bcephal-messenger-service
        image: localhost:5000/becphal-messenger-service-docker-image
        volumeMounts:
        - name: bcephal-messenger-repository
          mountPath: /opt/bcephal-messenger-repository
        env: 
        - name: SERVER_PORT
          value: "30526"
          value: "30527"
          value: "30524"
        ports:
        - containerPort: 30526 
        - containerPort: 30527 
        - containerPort: 30524
        
---
apiVersion: v1
kind: Service
metadata:
  name: bcephal-messenger-service
spec:
  selector:
    app: bcephal-messenger-service
  type: NodePort
  ports:  
    - name: test
      nodePort: 30526
      port: 8081
      targetPort: 30526
      protocol: TCP
    - name: tast
      nodePort: 30527
      port: 8082
      targetPort: 30527
      protocol: TCP
    - name: http
      nodePort: 30524
      port: 8080
      targetPort: 30524
      protocol: TCP
   
  
  


  

