apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://192.168.100.93.eureka:8761/eureka


---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
   app: eureka
spec:
  selector:
    app: eureka
  clusterIP: None
  ports:
     - port: 8761
       targetPort: 8761
 
---



apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  podManagementPolicy: "Parallel" 
  replicas: 2
  selector:
    matchLabels:
      app: eureka
    
  template:
    metadata:
      labels:
        app: eureka
    spec:
      volumes:
      - name: bcephal-registration-repository
        hostPath:
          path: /opt/bcephal-registration-repository
      containers:
      - name: eureka
        image: localhost:5000/becphal-registration-service-docker-image
        volumeMounts:
        - name: bcephal-registration-repository
          mountPath: /opt/bcephal-registration-repository

        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_PORT
          value: "8761"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EUREKA_INSTANCE_HOSTNAME
          value: ${MY_POD_NAME}.eureka   
  
---               

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761

  

