pipeline {
    agent any
	tools {
	   jdk 'JAVA_HOME'
	    gradle 'GRADLE_HOME'
		 dockerTool 'CustomeDocker'
	} 
	   
	environment {
	   DOCKER    = "${dockerTool1}/bin"
	    JAVA_HOME = "${jdk}"
		IP_HOST_ADDRESS= sh 'hostname -I | grep -oE "^(192\\.168\\.100\\.).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"'
		
	}
    
    stages {
        stage('Clone'){
             steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 1, noTags: true, reference: '', shallow: true, timeout: 120]], 
				submoduleCfg: [],userRemoteConfigs: [[credentialsId: 'e212babc-0713-415a-9848-da7292bb3718', url:
                 'http://saas1402fu.saas-secure.com/git/bcephal-registration-service.git']]])
			 }
        }
        stage('Build') {
		
            steps {	
            	sh 'chmod +x gradlew'                
               gradlew('clean', 'assemble')
				sh 'ls build/libs/'
            }
        }
		stage('Unit Tests') {
					steps {
					  script{
						 try {
							 dir('bcephal-registration-service'){
								
							  sh 'chmod +x gradle' 
							  sh './gradlew test '
							 
						  }
						}catch(exc) {
						 def summary = junit  skipPublishingChecks: true, testResults: '**/TEST-*.xml' 
							   sh "echo ${summary.totalCount}"
							   sh " echo ${summary.failCount}"
							   sh "echo ${summary.skipCount} " 
							   sh "echo ${summary.passCount} " 
							   def percentage = summary.passCount*100/summary.totalCount
							   sh "echo ${percentage}"
					     if ( ${percentage} < 98){
						    currentBuild.result = 'FAILURE'
					     }
						 currentBuild.result = 'SUCCESS'
						}
					 }
					}
				} 
        //stage('SonarQube analysis') {
            //steps {	
            	//withSonarQubeEnv('SonarQube') {
                  //  gradlew('sonarqube')
               // }
            //}
        //}    
		//stage('Assemble') {
         //   steps {
         //       gradlew('assemble')
          //      stash includes: '**/build/libs/*.jar', name: 'app'
          //  }
        //}
		// stage('Docker build image') {
        //    steps {
          //     dockerCmd "build -t becphal-registration-service-docker-image:${env.BUILD_NUMBER} ."
              // dockerCmd "save -o=becphal-registration-service-docker-image-${env.BUILD_NUMBER}.tar becphal-registration-service-docker-image:${env.BUILD_NUMBER}"
       //   }
      //  }
		//stage('Docker tag image latest') {
			//  steps {
			//   dockerCmd "tag becphal-registration-service-docker-image:${env.BUILD_NUMBER}  becphal-registration-service-docker-image:latest "
				   
			//   }
		//   }
		//stage('Docker ') {
       //   steps {
        //   dockerCmd "tag becphal-registration-service-docker-image localhost:5000/becphal-registration-service-docker-image "
               
          // }
       //  }
	  //  stage('Docker push image latest') {
          // steps {
             // dockerCmd "push localhost:5000/becphal-registration-service-docker-image"
               
           // }
        //}
		//stage('Docker run image') {
          // steps {
			
          //   dockerCmd "run  -tid -p 8761:8761  -v /opt/bcephal-registration-repository:/opt/bcephal-registration-repository -v /opt/bcephal-data:/opt/bcephal-data --env HOST_ADDRESS=${IP_HOST_ADDRESS} --name  becphal-registration-service  becphal-registration-service-docker-image"
         //  sh 'docker ps'  
         // }
       // }
		//stage('Deploy app'){
			//steps{
					//script{
						//kubernetesDeploy(configs:"deployment-registration-service.yml ", kubeconfigId:"kubeconfiguration")
					//}
				
			//}
		//}
	}
     post {
				always {
				 dir('/var/lib/jenkins/workspace/bcephal-registration-service/bcephal-registration-service/build/test-results/test/'){
					 junit  skipPublishingChecks: true, testResults: '**/TEST-*.xml'
					  sh 'ls'
				 }		 
			   }
			 failure {
				mail to: 'jwambo@moriset.com', subject: 'B-Cephal Configuration microservice build failed', body: 'B-Cephal Configuration microservice build failed.\nPlease fix!'
			}
		}
}

def gradlew(String... args) {
    sh "./gradlew ${args.join(' ')} -s"
}

def dockerCmd(args) {
    sh "echo ${tool 'CustomeDocker'}"
    sh "echo ${env.DOCKER_HOST}"
    sh "${tool 'CustomeDocker'}/bin/docker ${args}"
}