
ALTER TABLE BCP_CHAT_ITEM ADD COLUMN IF NOT EXISTS channelId BIGINT;

CREATE TABLE IF NOT EXISTS BCP_CHAT_ITEM_USER(
	id BIGINT not null,
	chatId BIGINT,
	lastItemId BIGINT,
	userId BIGINT,
	channelId BIGINT,
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS chat_item_user_seq START WITH 1 INCREMENT BY 1;