ALTER TABLE BCP_SPOT DROP COLUMN measureFilterItem;
ALTER TABLE BCP_SPOT ADD COLUMN measureId BIGINT;
ALTER TABLE BCP_SPOT ADD COLUMN measureFunction VARCHAR(50);
ALTER TABLE BCP_SPOT ADD COLUMN gridId BIGINT;