ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS cronExpression VARCHAR(255);
ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS scheduled BOOLEAN DEFAULT FALSE;
ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT FALSE;