DROP TABLE IF EXISTS BCP_MATERIALIZED_GRID_COLUMN; 
DROP TABLE IF EXISTS BCP_MATERIALIZED_GRID;
DROP SEQUENCE IF EXISTS mat_grid_column_seq;
DROP SEQUENCE IF EXISTS mat_grid_seq;


CREATE TABLE IF NOT EXISTS BCP_MATERIALIZED_GRID_COLUMN (
    id BIGINT not null,
	name VARCHAR(100) not null,
	type VARCHAR(100),
	grid BIGINT,
	category VARCHAR(100),
	position INTEGER not null,
	mandatory BOOLEAN DEFAULT FALSE,
	editable BOOLEAN DEFAULT FALSE,
	published BOOLEAN DEFAULT FALSE,
	show BOOLEAN DEFAULT FALSE,
	backgroundColor  INTEGER,
	foregroundColor  INTEGER,
	width  INTEGER,
	fixedType VARCHAR(255),	
	nbrOfDecimal INTEGER DEFAULT 2,
	usedSeparator BOOLEAN DEFAULT TRUE,
	defaultFormat VARCHAR(100),	
	groupBy VARCHAR(100),
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS mat_grid_column_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BCP_MATERIALIZED_GRID (
    id BIGINT not null,
	name VARCHAR(100) not null,
	visibleInShortcut BOOLEAN DEFAULT TRUE,
	bgroup BIGINT,
	category VARCHAR(100),
	editable BOOLEAN DEFAULT FALSE,
	published BOOLEAN DEFAULT FALSE,
	showAllRowsByDefault BOOLEAN DEFAULT FALSE,
	allowLineCounting BOOLEAN DEFAULT TRUE,
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS mat_grid_seq START WITH 1 INCREMENT BY 1;
