ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS invoiceValidationSequenceId BIGINT;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS useValidationDateAsInvoiceDate BOOLEAN;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS reprintPdfAtValidation BOOLEAN;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS draftReference TEXT;

UPDATE BCP_BILLING_INVOICE SET useValidationDateAsInvoiceDate = false, reprintPdfAtValidation = false;

ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS invoiceValidationSequenceId BIGINT;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS validateGeneratedInvoices BOOLEAN;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS useValidationDateAsInvoiceDate BOOLEAN;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS reprintPdfAtValidation BOOLEAN;

UPDATE BCP_BILLING_MODEL SET useValidationDateAsInvoiceDate = false, reprintPdfAtValidation = false, validateGeneratedInvoices = false;