ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS clientEmailCc TEXT;

ALTER TABLE BCP_ALARM_AUDIENCE ADD COLUMN IF NOT EXISTS emailType TEXT;
UPDATE BCP_ALARM_AUDIENCE SET emailType = 'MAIN' WHERE emailType IS NULL;

ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS appendicyGridType VARCHAR(50);
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS appendicyGridId BIGINT;

ALTER TABLE BCP_FILE_LOADER ADD COLUMN IF NOT EXISTS checkFileNameDuplication BOOLEAN;
UPDATE BCP_FILE_LOADER SET checkFileNameDuplication = false WHERE checkFileNameDuplication IS NULL;