ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN filter BIGINT;

CREATE TABLE BCP_ROUTINE_EXECUTOR (
    id BIGINT not null,
	routineId BIGINT,
	objectId BIGINT,
	objectType VARCHAR(100),
	type VARCHAR(25),
	position INTEGER,
	PRIMARY KEY (id)
);
CREATE SEQUENCE routine_executor_seq START WITH 1 INCREMENT BY 1;