ALTER TABLE BCP_TRANSFORMATION_ROUTINE_FIELD ADD COLUMN IF NOT EXISTS positionDimensionType VARCHAR(25);
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_FIELD ADD COLUMN IF NOT EXISTS replaceDimensionType VARCHAR(25);

UPDATE BCP_TRANSFORMATION_ROUTINE_FIELD SET positionDimensionType = 'ATTRIBUTE' WHERE positionDimensionType IS NULL;
UPDATE BCP_TRANSFORMATION_ROUTINE_FIELD SET replaceDimensionType = 'ATTRIBUTE' WHERE replaceDimensionType IS NULL;
