ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS useVat BOOLEAN;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS contactTitle VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS contactFirstname VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS contactLastname VARCHAR(100);