ALTER TABLE BCP_AUTO_RECO ADD COLUMN IF NOT EXISTS refreshAmounts BOOLEAN DEFAULT TRUE;
UPDATE BCP_AUTO_RECO SET refreshAmounts = TRUE WHERE refreshAmounts IS NULL;

CREATE TABLE IF NOT EXISTS BCP_AUTO_RECO_RANKING_ITEM(
	id BIGINT not null,
	autoRecoId BIGINT,
	dimensionType VARCHAR(50),
	dimensionId BIGINT,
	descending BOOLEAN DEFAULT TRUE,
	side VARCHAR(25),
	position INTEGER,
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS auto_reco_ranking_item_seq START WITH 1 INCREMENT BY 1;