ALTER TABLE BCP_JOIN_CONDITION ADD COLUMN IF NOT EXISTS verb VARCHAR(25);
ALTER TABLE BCP_JOIN_CONDITION ADD COLUMN IF NOT EXISTS openingBracket VARCHAR(25);
ALTER TABLE BCP_JOIN_CONDITION ADD COLUMN IF NOT EXISTS closingBracket VARCHAR(25);
ALTER TABLE BCP_JOIN_CONDITION ADD COLUMN IF NOT EXISTS comparator VARCHAR(25);