ALTER TABLE BCP_FORM_MODEL_MENU ADD COLUMN IF NOT EXISTS parentIcon VARCHAR(100);
ALTER TABLE BCP_FORM_MODEL_MENU ADD COLUMN IF NOT EXISTS newMenuIcon VARCHAR(100);
ALTER TABLE BCP_FORM_MODEL_MENU ADD COLUMN IF NOT EXISTS listMenuIcon VARCHAR(100);