ALTER TABLE BCP_USER_LOAD ADD COLUMN IF NOT EXISTS operationCode TEXT;
ALTER TABLE BCP_USER_LOADER_CONDITION ADD COLUMN IF NOT EXISTS decimalValue NUMERIC(19, 5);
ALTER TABLE BCP_USER_LOAD_LOG ADD COLUMN IF NOT EXISTS position INTEGER;

UPDATE BCP_USER_LOAD_LOG SET position = 0 WHERE position IS NULL;