ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS visibleColumnCount INTEGER DEFAULT 5;
UPDATE BCP_GRID SET visibleColumnCount = 5 WHERE visibleColumnCount IS NULL;

ALTER TABLE BCP_MATERIALIZED_GRID ADD COLUMN IF NOT EXISTS visibleColumnCount INTEGER DEFAULT 5;
UPDATE BCP_MATERIALIZED_GRID SET visibleColumnCount = 5 WHERE visibleColumnCount IS NULL;

ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS visibleColumnCount INTEGER DEFAULT 5;
UPDATE BCP_JOIN SET visibleColumnCount = 5 WHERE visibleColumnCount IS NULL;

ALTER TABLE BCP_SCHEDULER_PLANNER_ITEM ADD COLUMN IF NOT EXISTS maxRowCountPerFile INTEGER DEFAULT 10000;
UPDATE BCP_SCHEDULER_PLANNER_ITEM SET maxRowCountPerFile = 10000 WHERE maxRowCountPerFile IS NULL;
