ALTER TABLE BCP_SCHEDULER_PLANNER_ITEM ADD COLUMN IF NOT EXISTS gridType VARCHAR(50);
UPDATE BCP_SCHEDULER_PLANNER_ITEM SET gridType = 'REPORT_GRID' WHERE gridType IS NULL;

ALTER TABLE BCP_DASHBOARD ADD COLUMN IF NOT EXISTS defaultItem BIGINT;