ALTER TABLE BCP_GRID DROP COLUMN IF EXISTS published;
ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS published BOOLEAN;
ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS published BOOLEAN;

CREATE TABLE IF NOT EXISTS BCP_GRID_DIMENSION (
	id BIGINT not null,
	grid BIGINT,
	name VARCHAR (100) not null,	
	type VARCHAR (50),	
	position INTEGER,		
	dimensionId BIGINT,	
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,	
	PRIMARY KEY (id)		
);
CREATE SEQUENCE IF NOT EXISTS grid_dimension_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS BCP_GRID_PUBLICATION_LOG (
	id BIGINT not null,
	grid BIGINT,
	name VARCHAR (100),		
	operation VARCHAR (50),	
	username VARCHAR (50),	
    creationDate TIMESTAMP,	
	PRIMARY KEY (id)		
);
CREATE SEQUENCE IF NOT EXISTS grid_publication_log_seq START WITH 1 INCREMENT BY 1;