
ALTER TABLE BCP_CHAT_ITEM ADD COLUMN IF NOT EXISTS receiverId BIGINT;

ALTER TABLE BCP_CHAT_ITEM ADD COLUMN IF NOT EXISTS receiverType VARCHAR(50);

ALTER TABLE BCP_CHAT_ITEM DROP COLUMN receiverIdsImpl;

DROP TABLE IF EXISTS BCP_CHAT_RECEIVER;

DROP SEQUENCE IF EXISTS chat_receiver_seq;