ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS allowReplacementGrid BOOLEAN DEFAULT TRUE;
ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS replacementMatGridId BIGINT;
ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS replacementTargetType VARCHAR(50);
ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS replacementGridCreationtType VARCHAR(50);
ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS replacementMatGridName VARCHAR(255);
UPDATE BCP_ARCHIVE_CONFIGURATION SET allowReplacementGrid = TRUE WHERE allowReplacementGrid IS NULL;
UPDATE BCP_ARCHIVE_CONFIGURATION SET replacementTargetType = 'UNIVERSE' WHERE replacementTargetType IS NULL;
UPDATE BCP_ARCHIVE_CONFIGURATION SET replacementGridCreationtType = 'NEW' WHERE replacementTargetType IS NULL;


ALTER TABLE BCP_ARCHIVE ADD COLUMN IF NOT EXISTS allowReplacementGrid BOOLEAN DEFAULT TRUE;
ALTER TABLE BCP_ARCHIVE ADD COLUMN IF NOT EXISTS replacementMatGridId BIGINT;
ALTER TABLE BCP_ARCHIVE ADD COLUMN IF NOT EXISTS replacementTargetType VARCHAR(50);
UPDATE BCP_ARCHIVE SET allowReplacementGrid = TRUE WHERE allowReplacementGrid IS NULL;
UPDATE BCP_ARCHIVE SET replacementTargetType = 'UNIVERSE' WHERE replacementTargetType IS NULL;

ALTER TABLE BCP_MATERIALIZED_GRID_COLUMN ADD COLUMN IF NOT EXISTS role VARCHAR(50);
ALTER TABLE BCP_MATERIALIZED_GRID_COLUMN ADD COLUMN IF NOT EXISTS dimensionId BIGINT;
UPDATE BCP_MATERIALIZED_GRID_COLUMN SET role = 'NONE' WHERE role IS NULL;



