CREATE TABLE IF NOT EXISTS BCP_VARIABLE (
    id BIGINT not null,
	dataSourceType VARCHAR(100),
	dataSourceId BIGINT,
	dimensionType VARCHAR(100),	
	dimensionId BIGINT,	
	name VARCHAR(255),
	PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS variable_seq START WITH 1 INCREMENT BY 1;


ALTER TABLE BCP_ATTRIBUTE_FILTER_ITEM ADD COLUMN  IF NOT EXISTS itemType VARCHAR(100);

ALTER TABLE BCP_MEASURE_FILTER_ITEM ADD COLUMN   IF NOT EXISTS variable VARCHAR(255);

ALTER TABLE BCP_MEASURE_FILTER_ITEM ADD COLUMN  IF NOT EXISTS itemType VARCHAR(100);

ALTER TABLE BCP_PERIOD_FILTER_ITEM ADD COLUMN   IF NOT EXISTS variable VARCHAR(255);

ALTER TABLE BCP_PERIOD_FILTER_ITEM ADD COLUMN  IF NOT EXISTS itemType VARCHAR(100);

ALTER TABLE BCP_ATTRIBUTE_FILTER_ITEM ADD COLUMN   IF NOT EXISTS variable VARCHAR(255);

ALTER TABLE BCP_SPOT_FILTER_ITEM ADD COLUMN   IF NOT EXISTS variable VARCHAR(255);

ALTER TABLE BCP_SPOT_FILTER_ITEM ADD COLUMN  IF NOT EXISTS itemType VARCHAR(100);
