CREATE TABLE if not exists BCP_FORM_MODEL_BUTTON_ACTION (
    id BIGINT not null,
    buttonId BIGINT, 
    type VARCHAR(100),       
	fieldId BIGINT,	
	schedulerId BIGINT,	
	position INTEGER,
	active BOOLEAN,
	stringValue TEXT,	
	decimalValue DECIMAL (31, 14),	
	dateOperator VARCHAR(100), 
	dateValue TIMESTAMP,
	dateSign VARCHAR(100),
	dateNumber INTEGER,
	dateGranularity VARCHAR(100),	
	PRIMARY KEY (id)
);
CREATE SEQUENCE if not exists form_model_button_action_seq START WITH 1 INCREMENT BY 1;


ALTER TABLE BCP_ACCOUNTING_BOOKING_MODEL ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_ACCOUNTING_POSTING ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_ALARM ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_ARCHIVE ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_ARCHIVE_CONFIGURATION ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_GROUP ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_BILLING_MODEL_LOG ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_BILLING_RUN_OUTCOME ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_BILL_TEMPLATE ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_FILE_LOADER ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_TRANSFORMATION_ROUTINE ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_AUTO_RECO ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_SCHEDULER_PLANNER ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_DASHBOARD ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_DASHBOARD_REPORT ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_JOIN_LOG ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_MATERIALIZED_GRID ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_FORM_MODEL ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_LINK ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_SPREADSHEET ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_TASK ADD COLUMN IF NOT EXISTS description TEXT;
