ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS confirmAction BOOLEAN DEFAULT FALSE;
ALTER TABLE BCP_RECONCILIATION_JOIN_MODEL ADD COLUMN IF NOT EXISTS confirmAction BOOLEAN DEFAULT FALSE;
ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS confirmAction BOOLEAN DEFAULT FALSE;

    