ALTER TABLE BCP_SPOT ADD COLUMN IF NOT EXISTS gridType VARCHAR(50);
UPDATE BCP_SPOT SET gridType = 'UNIVERSE' WHERE gridType IS NULL;

ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_GRID SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_DASHBOARD_REPORT ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_DASHBOARD_REPORT ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_DASHBOARD_REPORT SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_TRANSFORMATION_ROUTINE ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_TRANSFORMATION_ROUTINE ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_TRANSFORMATION_ROUTINE SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS publicationDataSourceType VARCHAR(50);
UPDATE BCP_JOIN SET publicationDataSourceType = 'INPUT_GRID' WHERE publicationDataSourceType IS NULL;

ALTER TABLE BCP_ATTRIBUTE_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_ATTRIBUTE_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_ATTRIBUTE_FILTER_ITEM SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_MEASURE_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_MEASURE_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_MEASURE_FILTER_ITEM SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_PERIOD_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_PERIOD_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_PERIOD_FILTER_ITEM SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;

ALTER TABLE BCP_SPOT_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceType VARCHAR(50);
ALTER TABLE BCP_SPOT_FILTER_ITEM ADD COLUMN IF NOT EXISTS dataSourceId BIGINT;
UPDATE BCP_SPOT_FILTER_ITEM SET dataSourceType = 'UNIVERSE' WHERE dataSourceType IS NULL;


