ALTER TABLE BCP_BILLING_MODEL_PARAMETER ADD COLUMN IF NOT EXISTS globalParameter BOOLEAN DEFAULT FALSE;
ALTER TABLE BCP_BILLING_INVOICE_ITEM_INFO ADD COLUMN IF NOT EXISTS invoice BIGINT;
ALTER TABLE BCP_BILLING_INVOICE_ITEM_INFO ADD COLUMN IF NOT EXISTS globalParameter BOOLEAN DEFAULT FALSE;


UPDATE BCP_BILLING_MODEL_PARAMETER SET globalParameter = FALSE;
UPDATE BCP_BILLING_INVOICE_ITEM_INFO SET globalParameter = FALSE;








