ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS fileName TEXT;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS validationReference TEXT;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS validationDate TIMESTAMP;

ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS fileNameDescription TEXT;