ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS visibleInShortcut BOOLEAN DEFAULT TRUE;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS bgroup BIGINT;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS creationDate TIMESTAMP;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS modificationDate TIMESTAMP;
ALTER TABLE BCP_DOCUMENT ADD COLUMN IF NOT EXISTS username VARCHAR(100);
