CREATE TABLE IF NOT EXISTS BCP_JOIN_UNION_KEY_ITEM (
    id BIGINT not null,
	unionId BIGINT,
	position INTEGER,
	dimensionType VARCHAR(100),
	gridType VARCHAR(100),
	gridId BIGINT,
	columnId BIGINT,
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS join_union_key_item_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BCP_JOIN_UNION_KEY (
    id BIGINT not null,
	joinId BIGINT,
	position INTEGER,
	dimensionType VARCHAR(100),
	gridType VARCHAR(100),
	gridId BIGINT,
	columnId BIGINT,
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS join_union_key_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE BCP_MATERIALIZED_GRID ADD COLUMN IF NOT EXISTS userFilter BIGINT;
ALTER TABLE BCP_MATERIALIZED_GRID ADD COLUMN IF NOT EXISTS adminFilter BIGINT;