
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN IF NOT EXISTS spot BIGINT;
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN IF NOT EXISTS ascending BOOLEAN;
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN IF NOT EXISTS dimensionId BIGINT;
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN IF NOT EXISTS dimensionType VARCHAR(50);

CREATE TABLE IF NOT EXISTS BCP_TRANSFORMATION_ROUTINE_SPOT (
    id BIGINT not null,	
	dataSourceType VARCHAR(50),
	dataSourceId BIGINT,
	filter BIGINT,
	measureId BIGINT,
	measureFunction VARCHAR(255),
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS transformation_routine_spot_seq START WITH 1 INCREMENT BY 1;