ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS method VARCHAR(100);
ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS reconciliatedAmountLogGridId BIGINT;
ALTER TABLE BCP_RECONCILIATION_MODEL ADD COLUMN IF NOT EXISTS allowReconciliatedAmountLog BOOLEAN;
UPDATE BCP_RECONCILIATION_MODEL SET allowReconciliatedAmountLog = false WHERE allowReconciliatedAmountLog = null;