ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS merchantNumber VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS clientDoingBusinessAs VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS clientInternalNumber VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS creationDateBilling TIMESTAMP;