ALTER TABLE BCP_TRANSFORMATION_ROUTINE_FIELD ADD COLUMN IF NOT EXISTS dateFormat VARCHAR(25);
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_FIELD ADD COLUMN IF NOT EXISTS decimalSeparator VARCHAR(5);
UPDATE BCP_TRANSFORMATION_ROUTINE_FIELD SET dateFormat = 'dd/MM/yyyy' WHERE dateFormat IS NULL;
UPDATE BCP_TRANSFORMATION_ROUTINE_FIELD SET decimalSeparator = '.' WHERE decimalSeparator IS NULL;


ALTER TABLE BCP_TRANSFORMATION_ROUTINE_ITEM ADD COLUMN IF NOT EXISTS active BOOLEAN;
UPDATE BCP_TRANSFORMATION_ROUTINE_ITEM SET active = true WHERE active IS NULL;

