
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS driverDecimalNumber INTEGER;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS unitCostDecimalNumber INTEGER;
ALTER TABLE BCP_BILLING_MODEL ADD COLUMN IF NOT EXISTS billingAmountDecimalNumber INTEGER;

ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS driverDecimalNumber INTEGER;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS unitCostDecimalNumber INTEGER;
ALTER TABLE BCP_BILLING_INVOICE ADD COLUMN IF NOT EXISTS billingAmountDecimalNumber INTEGER;
