DROP TABLE IF EXISTS BCP_BILLING_INVOICE;
DROP TABLE IF EXISTS BCP_BILLING_INVOICE_ITEM;
DROP TABLE IF EXISTS BCP_BILLING_RUN_OUTCOME;
DROP TABLE IF EXISTS BCP_BILLING_MODEL_ENRICHMENT_ITEM;
DROP SEQUENCE IF EXISTS billing_invoice_item_seq;


CREATE TABLE BCP_BILLING_INVOICE_ITEM (
    id BIGINT not null,
	invoice BIGINT not null,	
	position INTEGER,	
	category TEXT,	
	description TEXT,	
	includeQuantity BOOLEAN,	
	quantity DECIMAL (31, 14),	
	unit VARCHAR(255),	
	includeUnitCost BOOLEAN,	
	unitCost DECIMAL (31, 14),	
	amount DECIMAL (31, 14),		
	vatRate DECIMAL (31, 14),
	currency VARCHAR(100),	
	billingQuantity DECIMAL (31, 14),	
	billingUnitCost DECIMAL (31, 14),	
	billingAmount DECIMAL (31, 14),		
	billingVatRate DECIMAL (31, 14),	
	subjectToVat BOOLEAN,	
	useUnitCost BOOLEAN,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE billing_invoice_item_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE BCP_BILLING_INVOICE (
    id BIGINT not null,
    name VARCHAR(100) not null,
    parent VARCHAR(100),
    type VARCHAR(50),
	file TEXT ,
	visibleInShortcut BOOLEAN DEFAULT TRUE,
	bgroup BIGINT,	
	status VARCHAR(100),
    reference  VARCHAR(100),
	runNumber  VARCHAR(100),
	orderReference  VARCHAR(100),
	communicationMessage  VARCHAR(100),
	departmentNumber  VARCHAR(100),
    clientContact  VARCHAR(100),
	clientNumber  VARCHAR(100),
	clientName  VARCHAR(100),
	clientLegalForm  VARCHAR(100),
	clientAdressStreet  VARCHAR(100),
	clientAdressPostalCode  VARCHAR(100),
	clientAdressCity  VARCHAR(100),
	clientAdressCountry  VARCHAR(100),
	clientVatNumber  VARCHAR(100),
	clientEmail  VARCHAR(100),
	clientPhone  VARCHAR(100),
	clientLanguage  VARCHAR(100) ,
	billingCompanyNumber  VARCHAR(100),
	billingCompanyName  VARCHAR(100),
	billingCompanyLegalForm  VARCHAR(100),
	billingCompanyAdressStreet  VARCHAR(100),
	billingCompanyAdressPostalCode  VARCHAR(100),
	billingCompanyAdressCity  VARCHAR(100),
	billingCompanyAdressCountry  VARCHAR(100),
	billingCompanyVatNumber  VARCHAR(100),
	billingCompanyEmail  VARCHAR(100),
	billingCompanyPhone  VARCHAR(100),
	amountWithoutVat DECIMAL (31, 14),
	vatAmount DECIMAL (31, 14),
	billingAmountWithoutVat  DECIMAL (31, 14),
	billingVatAmount  DECIMAL (31, 14),
	amountUnit  VARCHAR(100),
	billTemplateCode  VARCHAR(100),
	version  INTEGER,
	manuallyModified  BOOLEAN,
	subjectToVat  BOOLEAN,
	useUnitCost  BOOLEAN,
	pivotValues  VARCHAR(100),
	orderItems  BOOLEAN,
	orderItemsAsc  BOOLEAN,
	mailStatus  VARCHAR(100),
	description TEXT,
	repository TEXT,
	systemTemplate BOOLEAN,
	billingDate TIMESTAMP,
	invoiceDate TIMESTAMP,
	invoiceDate2 TIMESTAMP,
	dueDate TIMESTAMP,
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE BCP_BILLING_RUN_OUTCOME (
    id BIGINT not null,
	runNumber  VARCHAR(100),
	status VARCHAR(100),
	mode VARCHAR(100),
	username VARCHAR(100),
	invoiceCount BIGINT ,
	invoiceAmount   DECIMAL (31, 14),
	creditNoteCount BIGINT,
	creditNoteAmount DECIMAL (31, 14),
	periodFrom TIMESTAMP,
	periodTo TIMESTAMP,
	name VARCHAR(100),
	visibleInShortcut BOOLEAN DEFAULT TRUE,	
	bgroup BIGINT,	
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
	
);

CREATE TABLE BCP_BILLING_MODEL_ENRICHMENT_ITEM (
	id BIGINT not null,
	billing BIGINT,
	position BIGINT,
	decimalValue DECIMAL (31, 14),
	stringValue VARCHAR(100),
	dateOperator VARCHAR (25),
	dateValue Date,
	dateSign VARCHAR(100),
	dateNumber BIGINT,
	dateGranularity VARCHAR (25),
	sourceType VARCHAR(100),
	sourceId BIGINT,
	PRIMARY KEY (id)
);