ALTER TABLE BCP_UNION_GRID_COLUMN ADD COLUMN IF NOT EXISTS alignment VARCHAR(50);
ALTER TABLE BCP_JOIN_COLUMN ADD COLUMN IF NOT EXISTS alignment VARCHAR(50);
ALTER TABLE BCP_MATERIALIZED_GRID_COLUMN ADD COLUMN IF NOT EXISTS alignment VARCHAR(50);
ALTER TABLE BCP_GRID_COLUMN ADD COLUMN IF NOT EXISTS alignment VARCHAR(50);
ALTER TABLE BCP_FORM_MODEL_FIELD ADD COLUMN IF NOT EXISTS alignment VARCHAR(50);

UPDATE BCP_UNION_GRID_COLUMN SET alignment = 'Center' WHERE alignment is null;
UPDATE BCP_JOIN_COLUMN SET alignment = 'Center' WHERE alignment is null;
UPDATE BCP_MATERIALIZED_GRID_COLUMN SET alignment = 'Center' WHERE alignment is null;
UPDATE BCP_GRID_COLUMN SET alignment = 'Center' WHERE alignment is null;
UPDATE BCP_FORM_MODEL_FIELD SET alignment = 'Center' WHERE alignment is null;