ALTER TABLE BCP_BILLING_MODEL DROP COLUMN IF EXISTS invoiceDescription;

CREATE TABLE IF NOT EXISTS BCP_BILLING_DESCRIPTION (
    id BIGINT not null,
	billing BIGINT,
	description TEXT,
	locale VARCHAR(100),
	PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS billing_description_seq START WITH 1 INCREMENT BY 1;