ALTER TABLE BCP_RECONCILIATION_UNION_MODEL_GRID ADD COLUMN IF NOT EXISTS grille BIGINT;
ALTER TABLE BCP_RECONCILIATION_UNION_MODEL_GRID ADD COLUMN IF NOT EXISTS type VARCHAR(50);
UPDATE BCP_RECONCILIATION_UNION_MODEL_GRID SET type = 'UNION_GRID' WHERE type IS NULL;