-- ---------------------------- INITIATION -----------------------------------
-- ------------------------------------------------------------------------
-- ---------------------------- INITIATION -----------------------------------
-- ------------------------------------------------------------------------



CREATE TABLE BCP_PARAMETER (
    id BIGINT not null,
	code TEXT not null,
	parentCode TEXT,
	parameterType VARCHAR(50),	 		
	integerValue INTEGER,	
	longValue BIGINT,	
	decimalValue DECIMAL (31, 14),
	stringValue TEXT,	
	dateValue DATE,	
	booleanValue BOOLEAN,
	PRIMARY KEY (id)
);
CREATE SEQUENCE parameter_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE BCP_INCREMENTAL_NUMBER (
    id BIGINT not null,
	name TEXT not null,
	initialValue BIGINT, 
	incrementValue BIGINT, 
	minimumValue BIGINT,	
	maximumValue BIGINT,	
	currentValue BIGINT, 
	cycle BOOLEAN, 	
	size INTEGER,	
	prefix VARCHAR(100),	 	
	suffix VARCHAR(100),	
	visibleInShortcut BOOLEAN DEFAULT TRUE,
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
);
CREATE SEQUENCE incremental_number_seq START WITH 1 INCREMENT BY 1;


create domain clob as text;

CREATE TABLE BCP_MODEL (
    id BIGINT not null,
	name VARCHAR(100) not null,
	position INTEGER,
	visibleInShortcut BOOLEAN DEFAULT TRUE,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	diagramXml CLOB,		
	creationDate TIMESTAMP,
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
);
CREATE SEQUENCE model_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE BCP_ENTITY (
    id BIGINT not null,
	name VARCHAR(100) not null,
	model BIGINT not null,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	PRIMARY KEY (id)
);
CREATE SEQUENCE entity_seq START WITH 1 INCREMENT BY 1;


create table BCP_ATTRIBUTE (
	id BIGINT not null,
	name VARCHAR (100),
    defaultValue VARCHAR (100),
    declared BOOLEAN,
    incremantalValue BIGINT,
	position INTEGER,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	entity BIGINT,
	parent BIGINT,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE attribute_seq START WITH 1 INCREMENT BY 1;

create table BCP_ATTRIBUTE_VALUE (
	id BIGINT not null,
	name VARCHAR (100),
	position INTEGER,
	attribute BIGINT,
	parent BIGINT,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE attribute_value_seq START WITH 1 INCREMENT BY 1;


create table BCP_MEASURE (
	id BIGINT not null,
	name VARCHAR (100),
    defaultValue DECIMAL (31, 14),
	position INTEGER,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	parent BIGINT,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE measure_seq START WITH 1 INCREMENT BY 1;


create table BCP_PERIOD_NAME (
	id BIGINT not null,
	name VARCHAR (100),
    defaultValue DATE,
	position INTEGER,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	parent BIGINT,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE period_name_seq START WITH 1 INCREMENT BY 1;


create table BCP_CALENDAR_CATEGORY (
	id BIGINT not null,
	name VARCHAR (100),
	position INTEGER,
	visibleByAdminOnly BOOLEAN DEFAULT false,
	PRIMARY KEY (id)
);
CREATE SEQUENCE calendar_category_seq START WITH 1 INCREMENT BY 1;


create table BCP_CALENDAR_DAY (
	id BIGINT not null,
	category BIGINT,
	dayType VARCHAR (50),
    day INTEGER,
	month INTEGER,
	year INTEGER,
	position INTEGER,
	parent BIGINT,	
	PRIMARY KEY (id)
);
CREATE SEQUENCE calendar_day_seq START WITH 1 INCREMENT BY 1;





CREATE table BCP_UNIVERSE (
	ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		
	USERNAME VARCHAR (100),
	SOURCE_TYPE VARCHAR (50),
	SOURCE_ID BIGINT,
	SOURCE_NAME VARCHAR (100),	
	EXTERNAL_SOURCE_TYPE VARCHAR (50),
	EXTERNAL_SOURCE_REF	VARCHAR (100),
	EXTERNAL_SOURCE_ID BIGINT,		
	ISREADY	BOOLEAN DEFAULT true,	
	INCREMENTAL INTEGER,
	FREE_1 VARCHAR (255),
	FREE_2 VARCHAR (255),
	FREE_3 VARCHAR (255),
	FREE_4 VARCHAR (255),
	FREE_5 VARCHAR (255)
);

	