	
ALTER TABLE BCP_RECONCILIATION_UNION_MODEL ADD COLUMN IF NOT EXISTS confirmaction BOOLEAN DEFAULT FALSE;

ALTER TABLE BCP_UNION_GRID ADD COLUMN IF NOT EXISTS rowtype VARCHAR(50);

ALTER TABLE BCP_UNION_GRID_COLUMN ADD COLUMN IF NOT EXISTS dimensionid BIGINT;
ALTER TABLE BCP_UNION_GRID_COLUMN ADD COLUMN IF NOT EXISTS type VARCHAR(100);

ALTER TABLE BCP_WRITE_OFF_UNION_FIELD ADD COLUMN IF NOT EXISTS variablename TEXT;

ALTER TABLE BCP_RECONCILIATION_UNION_MODEL_ENRICHMENT ADD COLUMN IF NOT EXISTS variablename TEXT;