ALTER TABLE BCP_VARIABLE ADD COLUMN  IF NOT EXISTS bgroup Bigint;
ALTER TABLE BCP_VARIABLE ADD COLUMN  IF NOT EXISTS description TEXT;
ALTER TABLE BCP_VARIABLE ADD COLUMN  IF NOT EXISTS visibleInShortcut boolean;
ALTER TABLE BCP_VARIABLE ADD COLUMN  IF NOT EXISTS creationDate TIMESTAMP;
ALTER TABLE BCP_VARIABLE ADD COLUMN  IF NOT EXISTS modificationDate TIMESTAMP;
