ALTER TABLE BCP_DASHBOARD_ITEM ADD COLUMN IF NOT EXISTS linkedLabel VARCHAR(512);
ALTER TABLE BCP_DASHBOARD_ITEM ADD COLUMN IF NOT EXISTS linkedFunctionality VARCHAR(256);
ALTER TABLE BCP_DASHBOARD_ITEM ADD COLUMN IF NOT EXISTS linkedFunctionalityId BIGINT;
ALTER TABLE BCP_GRID ADD COLUMN IF NOT EXISTS reportId BIGINT;


