ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS rowType VARCHAR(50);
ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS debit BOOLEAN DEFAULT FALSE;
ALTER TABLE BCP_JOIN ADD COLUMN IF NOT EXISTS credit BOOLEAN DEFAULT FALSE;

ALTER TABLE BCP_RECONCILIATION_JOIN_MODEL_GRID ADD COLUMN IF NOT EXISTS userColumnId BIGINT;
ALTER TABLE BCP_RECONCILIATION_JOIN_MODEL_GRID ADD COLUMN IF NOT EXISTS modeColumnId BIGINT;