ALTER TABLE BCP_FILE_LOADER_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_SCHEDULER_PLANNER_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_JOIN_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_RECONCILIATION_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_BILLING_INVOICE_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_BILLING_RUN_OUTCOME ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_TRANSFORMATION_ROUTINE_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);
ALTER TABLE BCP_RECONCILIATION_LOG ADD COLUMN IF NOT EXISTS operationCode VARCHAR(100);