
ALTER TABLE BCP_WRITE_OFF_UNION_MODEL ADD COLUMN IF NOT EXISTS writeOffGridId BIGINT;

ALTER TABLE BCP_WRITE_OFF_UNION_FIELD ADD COLUMN IF NOT EXISTS secondDimensionId BIGINT;

ALTER TABLE BCP_WRITE_OFF_UNION_FIELD_VALUE ADD COLUMN IF NOT EXISTS variablename TEXT;