DROP TABLE IF EXISTS BCP_BILLING_MODEL_TEMPLATE;
DROP SEQUENCE IF EXISTS billing_model_template_seq;


CREATE TABLE IF NOT EXISTS BCP_BILLING_MODEL_TEMPLATE (
	id BIGINT not null,
	modelId BIGINT,
	templateId BIGINT,
	filter BIGINT,
	position BIGINT,
	PRIMARY KEY (id)
);
CREATE SEQUENCE billing_model_template_seq START WITH 1 INCREMENT BY 1;