/**
 * 
 */
package com.moriset.bcephal.dashboard.domain;

/**
 * @author Joseph Wambo
 *
 */
public enum DashboardItemType {

	CHART, DRILL_DOWN_GRID, PIVOT_TABLE, REPORT_PUBLICATION, REPORT_GRID,
	PROJECT_BROWSER, INPUT_GRID_BROWSER, REPORT_GRID_BROWSER, TRANSFORMATION_TREE_BROWSER,
	FORM_BROWSER, LOADER_BROWSER,BILLING_MODEL_BROWSER, BILLING_TEMPLATE_LIST,
	BOOKING_BROWSER, DASHBOARD_HOME_PAGE, HOME_PAGE, DASHBOARD_BROWSER,
	PIVOT_TABLE_BROWSER, CHART_BROWSER, EMPTY_TYPE, BROWSER_REPORTING_JOIN,BROWSER_SPOT,
	PROFIL_LIST,ADMIN_SCHEDULER_BROWSER,BROWSER_INCREMENTAL_NUMBER,BROWSER_USER,BROWSER_CLIENT,
	BROWSER_MESSAGE_LOG,ARCHIVE_CONFIGURATION_BROWSER,BROWSER_ARCHIVE_LOG,ARCHIVE_BROWSER, 
	BROWSER_BOOKING_MODEL_LOG, BROWSER_SCHEDULED_BOOKING,BROWSER_BOOKING_MODEL,POSTING_LIST,
	LIST_CREDIT_NOTE, LIST_INVOICE,SCHEDULED_MODEL_BROWSER,BROWSER_SCHEDULED_ROUTINE,BROWSER_SCHEDULED_TRANSFORMATION_TREE,
	BROWSER_TRANSFORMATION_ROUTINE,BROWSER_REPORT_SCHEDULED_ALARM,BROWSER_REPORT_ALARM,BROWSER_REPORT_PUBLICATION,
	BROWSER_REPORTING_JOIN_LOG,MATERIALIZED_BROWSER,RECONCILIATION_FILTER_BROWSER,RECONCILIATION_AUTO_BROWSER,
	BROWSER_SCHEDULER_PLANNER,BROWSER_TASK, BROWSER_REPORTING_JOIN_EDIT,BROWSER_REPORT_INPUT_NEW,
	BROWSER_REPORT_STANDALONE_NEW,RECONCILIATION_MODEL_BROWSER,FORM_BROWSER_ITEM,SOURCING_USER_LOAD_BROWSER,PRESENTATION;

	public boolean isChart() {
		return this == CHART;
	}

	public boolean isPivotTable() {
		return this == DashboardItemType.PIVOT_TABLE;
	}

	public boolean isDrillDownGrid() {
		return this == DRILL_DOWN_GRID;
	}

	public boolean isReportPublication() {
		return this == REPORT_PUBLICATION;
	}

	public boolean isReportGrid() {
		return this == REPORT_GRID;
	}

}
