apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcephal-security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcephal-security-service
    
  template:
    metadata:
      labels:
        app: bcephal-security-service
    spec:
      volumes:
      - name: bcephal-security-repository
        hostPath:
          path: /opt/bcephal-security-repository
      containers:
      - name: bcephal-security-service
        image: localhost:5000/becphal-security-service-docker-image
        volumeMounts:
        - name: bcephal-security-repository
          mountPath: /opt/bcephal-security-repository
        env: 
        - name: SERVER_PORT
          value: "30523"
        ports:
        - containerPort: 30523 
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: bcephal-security-service
spec:
  selector:
    app: bcephal-security-service
  type: NodePort
  ports:  
    - name: http
      nodePort: 30523
      port: 8080
      targetPort: 30523
      protocol: TCP
   
  
  


  

