
-- Table: public.batch_job_execution_params

-- DROP TABLE public.batch_job_execution_params;

ALTER TABLE public.batch_job_execution_params ADD COLUMN IF NOT EXISTS PARAMETER_NAME VARCHAR(100);
ALTER TABLE public.batch_job_execution_params ADD COLUMN IF NOT EXISTS PARAMETER_TYPE VARCHAR(100);
ALTER TABLE public.batch_job_execution_params ADD COLUMN IF NOT EXISTS PARAMETER_VALUE VARCHAR(2500);

ALTER TABLE batch_job_execution_params ALTER COLUMN TYPE_CD DROP NOT NULL;
ALTER TABLE batch_job_execution_params ALTER COLUMN KEY_NAME DROP NOT NULL;

ALTER TABLE BATCH_STEP_EXECUTION ADD COLUMN IF NOT EXISTS CREATE_TIME TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN START_TIME DROP NOT NULL;
