ALTER TABLE BCP_ALARM_MESSAGE_LOG_FAIL ADD COLUMN IF NOT EXISTS automaticMailModelName TEXT;
ALTER TABLE BCP_ALARM_MESSAGE_LOG_SUCCESS ADD COLUMN IF NOT EXISTS automaticMailModelName TEXT;
ALTER TABLE BCP_ALARM_MESSAGE_LOG_TO_SEND ADD COLUMN IF NOT EXISTS automaticMailModelName TEXT;