apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcephal-settings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcephal-settings-service
    
  template:
    metadata:
      labels:
        app: bcephal-settings-service
    spec:
      volumes:
      - name: bcephal-settings-repository
        hostPath:
          path: /opt/bcephal-settings-repository
      containers:
      - name: bcephal-settings-service
        image: localhost:5000/becphal-settings-service-docker-image
        volumeMounts:
        - name: bcephal-settings-repository
          mountPath: /opt/bcephal-settings-repository

        ports:
        - containerPort: 32013
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: bcephal-settings-service
spec:
  selector:
    app: bcephal-settings-service
  type: NodePort
  ports:  
    - name: http
      nodePort: 32013
      port: 32013
      targetPort: 32013
      protocol: TCP
   
  
  


  

